# Generated by Django 5.0.7 on 2024-08-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventclub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap', models.CharField(max_length=50)),
                ('pic1', models.ImageField(upload_to='assets/images')),
                ('pic2', models.ImageField(upload_to='assets/images')),
                ('pic3', models.ImageField(upload_to='assets/images')),
                ('pic4', models.ImageField(upload_to='assets/images')),
                ('pic5', models.ImageField(upload_to='assets/images')),
            ],
        ),
    ]
